name: root_package
description: The root package
version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.1.0
  my_package:

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
